const fs = require("fs");

// فایل متنی آموزشی
const inputFile = "data.txt"; // هر جمله یک خط

// خواندن متن آموزشی
const text = fs.readFileSync(inputFile, "utf8").toLowerCase().replace(/\n/g, ' ');

// تابع ساخت زنجیره مارکوف
function buildMarkovChain(text, n=2) {
  const words = text.split(/\s+/);
  const chain = {};

  for (let i = 0; i <= words.length - n; i++) {
    const key = words.slice(i, i + n).join(" ");
    const next = words[i + n];
    if (!chain[key]) chain[key] = [];
    if (next) chain[key].push(next);
  }
  return chain;
}

// تابع تولید جمله با مارکوف
function generateSentence(chain, n=2, maxWords=50) {
  const keys = Object.keys(chain);
  let key = keys[Math.floor(Math.random() * keys.length)];
  let result = key.split(" ");

  for (let i = 0; i < maxWords; i++) {
    const nextWords = chain[key];
    if (!nextWords || nextWords.length === 0) break;
    const next = nextWords[Math.floor(Math.random() * nextWords.length)];
    result.push(next);
    key = result.slice(result.length - n, result.length).join(" ");
  }

  return result.join(" ");
}

// ساخت مدل
const markovChain = buildMarkovChain(text);

// ذخیره مدل روی دیسک (می‌تونی بعداً با frontend بارگذاری کنی)
fs.writeFileSync("model.json", JSON.stringify(markovChain, null, 2));
console.log("✅ مدل ساخته شد و در model.json ذخیره شد");

// تولید یک جمله نمونه
console.log("نمونه جمله تولیدی:", generateSentence(markovChain));
